### ISSUE TITLE
Old zipballs no longer available

### ISSUE THREAD

**Issue by alienscience** [avh4-experimental/elm-transducers#8]
Hello,
  We have an Elm project whose Jenkins builds failed with the following error this morning:
```
    07:17:43 Error: The following HTTP request failed.
    07:17:43 <https://github.com/avh4/elm-transducers/zipball/3.0.1/>
    07:17:43 
    07:17:43 404: Not Found
```
It appears that the project has been reset to version 1:0:
   https://github.com/avh4-experimental/elm-transducers/blob/master/elm.json#L6

Is this something we need to workaround on our side or is there something you can do to restore the URL?

Many thanks for your help.

**Comment by avh4** [comment]
Hmm, Elm doesn't seem to support renaming packages at all, so I'm trying to find some hack that will work...   I tried re-adding the 3.0.1 tag.  Let me know if that works.

**Comment by alienscience** [comment]
Many thanks for the quick reply. I tried again and we no longer get a `404`. However, there is still an error with elm-package:
```
Error: Problem when downloading the avh4/elm-transducers 3.0.1 code.
```
I tried renaming the dependency to `avh4-experimental/elm-transducers` and that also fails:
```
Error: Could not find any packages named avh4-experimental/elm-transducers.

Here are some packages that have similar names:

    avh4-experimental/elm-layout
    avh4/elm-transducers
    avh4-experimental/elm-compose-programs
    sawaken-experiment/elm-lisp-parser

```

If we find a workaround I will add it to this bug report.

**Comment by avh4** [comment]
Hrm, that sucks :(

Maybe Elm 0.18 depends on the filename of the resulting file and the redirect is confusing it?  That seems unlikely, but in any case I just tried forking `avh4-experimental/elm-transducers` back to `avh4/elm-transducers`.  @alienscience  Let me know if that fixes things.

**Comment by avh4** [comment]
I just tried making an empty folder, and then with Elm 0.18:
```bash
elm-package install avh4/elm-transducers
```

and it worked for me.  So hopefully it is fixed  (at least until the new package name gets up to a 3.0.1 version, in which case I guess the Elm 0.18 version will break again, but I don't expect to be doing new major versions any time soon).

@alienscience  But let me know if it works for you now.

**Comment by alienscience** [comment]
I am sorry for the slow reply. This worked..

Many thanks for the help.
